services:
  n8n:
    image: n8nio/n8n
    environment: 
        - N8N_COMMUNITY_PACKAGES_ALLOW_MODE_USAGE=true
    container_name: n8n
    ports:
      - 5678:5678
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  n8n_data:
